export const GLOBAL = {
  USER: {
    INIT: 'GLOBAL.USER.INIT',
    UPDATE_POINT: 'GLOBAL.USER.UPDATE_POINT',
  },
}

// 作品
export const WORK = {
  CATE: {
    INIT: 'WORK.CATE.INIT',
    ADD: 'WORK.CATE.ADD',
  },
  TAG: {
    INIT: 'WORK.TAG.INIT',
  },
}

// 个人中心
export const CENTER = {
  INITIALIZE: 'CENTER.INITIALIZE',
  SETPAGINATE: 'CENTER.SETPAGINATE',
  LIST_UPDATE: 'CENTER.UPDATELIST',
  LINK_UPDATE: 'CENTER.UPDATELINK',
  LOAD_LOCK: 'CENTER.LOCKLOAD',
}


export const MESSAGE = {
  COUNT: {
    INIT: 'MESSAGE.COUNT.INIT',
    UPDATE: 'MESSAGE.COUNT.UPDATE',
  },
  SYSTEM: {
    INIT: 'MESSAGE.SYSTEM.INIT',
    DELETE: 'MESSAGE.SYSTEM.DELETE',
  },
  PRIVATE: {
    INIT: 'MESSAGE.PRIVATE.INIT',
    UPDATE: 'MESSAGE.PRIVATE.UPDATE',
    DELETE: 'MESSAGE.PRIVATE.DELETE',
    HISTORY: {
      INIT: 'MESSAGE.PRIVATE.HISTORY.INIT',
      UPDATE: 'MESSAGE.PRIVATE.HISTORY.UPDATE',
      RESET: 'MESSAGE.PRIVATE.HISTORY.RESET',
    },
  },
  SAY: {
    INIT: 'MESSAGE.SAY.INIT',
  },
}

export const POINT = {
  TASK: {
    INIT: 'POINT.TASK.INIT',
    UPDATE: 'POINT.TASK.UPDATE',
  },
  LOG: {
    INIT: 'POINT.LOG.INIT',
  },
  EXCHANGE: {
    INIT: 'POINT.EXCHANGE.INIT',
  },
  RECORD: {
    INIT: 'POINT.RECORD.INIT',
  },
}

export const PURCHASE = {
  ORDERS: {
    INIT: 'PURCHASE.ORDERS.INIT',
    DELETE: 'PURCHASE.ORDERS.DELETE',
  },
}

export const CERTIFICATE = {
  INIT: 'CERTIFICATE.INIT',
}


// 高级编辑模块 Edit
export const EDIT = {
  GET_PANOINFO: 'EDIT.GET_PANOINFO',

  // Functions组件控制
  MODAL: {
    OPEN: 'EDIT.MODAL.OPEN',
    CLOSE: 'EDIT.MODAL.CLOSE',
  },

  // Logo
  LOGO: {
    INITIALIZE: 'edit/logo/initialize',
  },

  // 作者
  AUTHOR: {
    INITIALIZE: 'edit/author/initialize',
  },

  // 素材模块
  MATERIAL: {
    CHANGE: 'EDIT.MATERIAL.CHANGE',
    INIT: 'EDIT.MATERIAL.INIT',
    CREATE: 'EDIT.MATERIAL.CREATE',
    UPDATE: 'EDIT.MATERIAL.UPDATE',
    REMOVE: 'EDIT.MATERIAL.REMOVE',
    INVOKE: 'EDIT.MATERIAL.INVOKE',

    SELECT: 'EDIT.MATERIAL.SELECT',
    RESET: 'EDIT.MATERIAL.RESET',
  },

  // 物品3D
  ROTATE: {
    CATE: {
      INIT: 'EDIT.ROTATE.CATE.INIT',
      SELECT: 'EDIT.ROTATE.CATE.SELECT',
      CREATE: 'EDIT.ROTATE.CATE.CREATE',
      UPDATE: 'EDIT.ROTATE.CATE.UPDATE',
      REMOVE: 'EDIT.ROTATE.CATE.REMOVE',
    },

    CREATE: 'EDIT.ROTATE.CREATE',
    UPDATE: 'EDIT.ROTATE.UPDATE',
    REMOVE: 'EDIT.ROTATE.REMOVE',
  },

  // 场景模块
  SCENE: {
    INIT: 'EDIT.SCENE.INIT',
    UPDATE: 'EDIT.SCENE.UPDATE',
    DELETE: 'EDIT.SCENE.DELETE',
  },

  // 菜单管理
  MENU: {
    INIT: 'EDIT.MENU.INIT',
    LOCATE: 'EDIT.MENU.LOCATE',
    CREATE: 'EDIT.MENU.CREATE',
    DELETE: 'EDIT.MENU.DELETE',
    PREPARE_EDITION: 'EDIT.MENU.PREPARE_EDITION',
    FINISH_EDITION: 'EDIT.MENT.FINISH_EDITION',
    PATCH_INFO: 'EDIT.MENU.PATCH_INFO',
    REPLACE_LIST: 'EDIT.MENU.REPLACE_LIST',
  },

  // 导览图
  TOUR: {
    INCREASE: 'EDIT.TOUR.INCREASE',
    DECREASE: 'EDIT.TOUR.DECREASE',
  },

  // 热点模块
  HOTSPOTS: {
    INIT: {
      ICON: 'EDIT.HOTSPOTS.INIT.ICON',
      SPOTS: 'EDIT.HOTSPOTS.INIT.SCENE',
    },
    CREATE: 'EDIT.HOTSPOTS.CREATE',
    UPDATE: 'EDIT.HOTSPOTS.UPDATE',
    REMOVE: 'EDIT.HOTSPOTS.REMOVE',
    SELECT: {
      ICON: 'EDIT.HOTSPOTS.SELECT.ICON',
    },
    RESET: {
      ICON: 'EDIT.HOTSPOTS.RESET.ICON',
    },
  },
}
